// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package frc.robot.commands.SmartCommands.Transistions;
import edu.wpi.first.wpilibj2.command.ParallelCommandGroup;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.Constants;
import frc.robot.SetPoints;
import frc.robot.commands.VoidBanisher;
import frc.robot.commands.ArmCommands.ArmGoToPosition;
import frc.robot.commands.ArmCommands.ArmGoToPositionAndHold;
import frc.robot.commands.DrivetrainCommands.DriveAmountWhileCollecting;
import frc.robot.commands.ElevatorCommands.ElevatorGoToPosition;
import frc.robot.commands.ElevatorCommands.ElevatorGoToPositionAndHold;
import frc.robot.commands.WristCommands.WristGoToPosition;
import frc.robot.commands.WristCommands.WristGoToPositionAndHold;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.intake;
import frc.robot.subsystems.wrist;
import frc.robot.subsystems.arm;
import frc.robot.subsystems.drivetrain;
import frc.robot.subsystems.elevator;
import frc.robot.commands.IntakeCommands.*;
import frc.robot.commands.SmartCommands.ClimbPoseBack;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */

public class ScoreToCubeWithArmFlip extends ParallelCommandGroup {
   // public intake intake;

    

    public ScoreToCubeWithArmFlip(double amount,double xSpeed, double ySpeed,intake intake,drivetrain drivetrain, wrist wrist,arm arm,elevator elevator){

    
    addCommands(
    new ClimbPoseBack(elevator, intake, wrist, arm),
    new DriveAmountWhileCollecting(intake, drivetrain,amount,xSpeed,ySpeed,0.2, true)//x = forward, y = strafe
    );
    }

    @Override
    public boolean runsWhenDisabled() {
        
        return false;

   
    }
}
