// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package frc.robot.commands.SmartCommands.Auto;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.commands.DrivetrainCommands.Drive2AmountsWithStrafeAndDriveUntilBalancedBackwards;
import frc.robot.commands.DrivetrainCommands.Drive3SpeedsAtDistancesWithArmAndWrist;
import frc.robot.commands.DrivetrainCommands.DriveAmount;
import frc.robot.commands.DrivetrainCommands.DriveAmountAndDriveUntilBalanced;
import frc.robot.commands.DrivetrainCommands.DriveAmountAndDriveUntilBalancedBackwards;
import frc.robot.commands.DrivetrainCommands.DriveAmountAtDifferentSpeedsAfterDistanceMovingArmAndWrist;
import frc.robot.commands.DrivetrainCommands.DriveAmountWhileCollecting;
import frc.robot.commands.DrivetrainCommands.DriveAmountWithStrafeAndDriveUntilBalancedBackwards;
import frc.robot.commands.DrivetrainCommands.DriveUntilBalanced;
import frc.robot.commands.DrivetrainCommands.StrafeAmount;
import frc.robot.commands.ElevatorCommands.ElevatorGoToPosition;
import frc.robot.commands.IntakeCommands.IntakeCube;
import frc.robot.commands.IntakeCommands.IntakeMotorGo;
import frc.robot.commands.SmartCommands.ClimbPoseBack;
import frc.robot.commands.SmartCommands.CollectFloorPoseBack;
import frc.robot.commands.SmartCommands.DriveAmountUntilBalancedAndArmClimbParallel;
import frc.robot.commands.SmartCommands.HomePose;
import frc.robot.commands.SmartCommands.Scores.ScoreHighCubePose;
import frc.robot.subsystems.elevator;
import frc.robot.subsystems.intake;
import frc.robot.subsystems.arm;
import frc.robot.subsystems.drivetrain;
import frc.robot.commands.SmartCommands.Balance;

import frc.robot.SetPoints;

import frc.robot.subsystems.wrist;
import frc.robot.subsystems.leds;
    
/**
 *
 */
public class RedHighCubeAndTaxiAndPickupAndEngage extends SequentialCommandGroup {

  

    public RedHighCubeAndTaxiAndPickupAndEngage(intake intake, wrist wrist, arm arm, elevator elevator, drivetrain drivetrain, leds leds){

    addCommands(
        
    new ScoreHighCubePose(intake, wrist, arm, elevator),
    new IntakeMotorGo(intake, -0.2).withTimeout(.1),
    new ElevatorGoToPosition(elevator, SetPoints.ElevatorHome),
    /*new Drive3SpeedsAtDistancesWithArmAndWrist(drivetrain, arm, wrist, 
    180, 20,
     -0.12, -0.37, 
    0,0.05,
    SetPoints.armChargeBack, SetPoints.WristChargeBack,
    -0.25,-0.1,170),
    */
    new IntakeMotorGo(intake, 0.5),
    new DriveAmountAtDifferentSpeedsAfterDistanceMovingArmAndWrist(drivetrain, arm, wrist, 
    185, 20,
     -0.12, -0.37, 
    -0,-0.06,
    SetPoints.armChargeBack, SetPoints.WristChargeBack),
    new edu.wpi.first.wpilibj2.command.WaitCommand(0.5),
    new Drive2AmountsWithStrafeAndDriveUntilBalancedBackwards(drivetrain, 0.35, 0.6, 0.3, 70, 55)
    
    
    );
    }

    @Override
    public boolean runsWhenDisabled() {
    
        return false;

    }
}
