// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package frc.robot.commands.SmartCommands;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.Constants;
import frc.robot.SetPoints;
import frc.robot.commands.VoidBanisher;
import frc.robot.commands.ArmCommands.ArmGoToPosition;
import frc.robot.commands.ElevatorCommands.ElevatorGoToPosition;
import frc.robot.commands.WristCommands.WristGo;
import frc.robot.commands.WristCommands.WristGoToPosition;

import frc.robot.subsystems.intake;
import frc.robot.subsystems.elevator;
import frc.robot.subsystems.wrist;
import frc.robot.subsystems.arm;
import frc.robot.commands.IntakeCommands.*;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.ParallelCommandGroup;

/**
 *
 */

public class HomePoseParallel extends SequentialCommandGroup {
   // public intake intake;

   

    public HomePoseParallel(elevator elevator,intake intake, wrist wrist,arm arm){

 
    addCommands(
    new ElevatorGoToPosition(elevator,SetPoints.ElevatorHome),
    new WristArmParallel(wrist, arm, SetPoints.WristHome, SetPoints.armHome),
    // new IntakeMotorGo(intake, 0.2).withTimeout(0.3),
    // new IntakeCone(intake,.2),
    new IntakeMotorGo(intake, 0.05)
    


    );
    }

    @Override
    public boolean runsWhenDisabled() {
        
        return false;

    }
}
